### ISSUE TITLE
bug when opening a note in neovim

### ISSUE THREAD

**Issue by PutaMadre1337** [armand-sauzay/note#14]
When I open notes through neovim, the application terminates with the error: "Error: error reading input: read /dev/stdin: resource temporarily unavailableexit status 1". If I use regular vim to open notes, there is no such error and everything works as it should.

**Comment by armandsauzay** [comment]
Thanks for opening this issue. Note now properly supports multiple editors through a fallback chain:

1. Your configured editor in `~/.config/note/config.yaml`
2. `NOTE_EDITOR` environment variable
3. `VISUAL` environment variable
4. `EDITOR` environment variable
5. `/usr/bin/vi` if it exists
6. `/bin/ed` as a final fallback

You can now:
1. Check your current editor configuration with `note --config`
2. Set your preferred editor (including neovim) in the config file:

Fixed in #16 


Feel free to re-open if it still causes issues 🙏
